<?php

namespace ContainerQrzwV87;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Classe\Search' shared autowired service.
     *
     * @return \App\Controller\Classe\Search
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Classe'.\DIRECTORY_SEPARATOR.'Search.php';

        return $container->services['App\\Controller\\Classe\\Search'] = new \App\Controller\Classe\Search();
    }
}
