<?php

namespace ContainerHHaa8Wl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterCollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PFJgvwM.EasyCorp\Bundle\EasyAdminBundle\Collection\FilterCollection' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Collection\FilterCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PFJgvwM": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Collection\\FilterCollection" but no such service exists.');
    }
}
