<?php

namespace ContainerPFp1H4A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UN56L3JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UN56L3J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UN56L3J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cart' => ['services', 'App\\Controller\\Classe\\Cart', 'getCartService', true],
        ], [
            'cart' => 'App\\Controller\\Classe\\Cart',
        ]);
    }
}
