<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC8lcQvo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC8lcQvo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC8lcQvo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC8lcQvo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC8lcQvo\App_KernelDevDebugContainer([
    'container.build_hash' => 'C8lcQvo',
    'container.build_id' => 'a5c5b590',
    'container.build_time' => 1637536675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC8lcQvo');
