<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPFp1H4A\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPFp1H4A/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPFp1H4A.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPFp1H4A\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPFp1H4A\App_KernelDevDebugContainer([
    'container.build_hash' => 'PFp1H4A',
    'container.build_id' => '4dd6753d',
    'container.build_time' => 1637528159,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPFp1H4A');
